 
[general]
scraperwebscripturldownload=
showdetailinfo=0000
trace_target01=3,xtracegen.dyndns.org:10001
trace_target02=
trace_target03=
trace_target04=
trace_target05=3,*:10001
 
[check resources hardware]
memstatuscheckcadenceseconds=30
memstatuslimitpercent=5
cpuusagecheckcadenceseconds=20
cpuusagelimitpercent=70
cpuusageprocessname=unittests
 
[internet services]
checkinternetstatuscadenceseconds=30
checkipschangecadenceminutes=60
updatetimebyntpcadencehours=4
updatetimentpserver01=1.es.pool.ntp.org
updatetimentpserver02=1.europe.pool.ntp.org
updatetimentpserver03=3.europe.pool.ntp.org
updatetimentpmeridiandifference=25
updatetimentpusedaylightsaving=yes
 
[dns resolved]
host_resolved01=
host_resolved02=
host_resolved03=
host_resolved04=
host_resolved05=
host_resolved06=
host_resolved07=
host_resolved08=
host_resolved09=
host_resolved10=
dns_server01=
dns_server02=
dns_server03=
 
[dyndns manager]
url01=
url02=
url03=
url04=
url05=
url06=
url07=
url08=
url09=
url10=
url11=
url12=
url13=
url14=
url15=
 
[alerts]
isactive=no
smtp_isactive=no
condition01=
condition02=
condition03=
condition04=
condition05=
condition06=
condition07=
condition08=
condition09=
condition10=
smtp_url=
smtp_port=0
smtp_login=
smtp_password=
smtp_sender=
smtp_recipient01=
smtp_recipient02=
smtp_recipient03=
smtp_recipient04=
smtp_recipient05=
sms_isactive=no
sms_recipient01=
sms_recipient02=
sms_recipient03=
sms_recipient04=
sms_recipient05=
web_isactive=no
web_isuseget=no
web_recipient01=
web_recipient02=
web_recipient03=
web_recipient04=
web_recipient05=
udp_isactive=no
udp_port=0
udp_recipient01=
udp_recipient02=
udp_recipient03=
udp_recipient04=
udp_recipient05=
 
[log]
isactive=yes
backupisactive=yes
backupmaxfiles=10
backupiscompress=yes
activesectionsID=Ini,General,Status,End
levelmask=000F
maxsize=3000
reductionpercent=10
 
;-------------------------------------------------------
;Database config
;-------------------------------------------------------
[database]
url=                                                        ;URL for database
port=0                                                      ;Port for database
databasename=                                               ;Database Name
user=
password=
timeoutconnection=30
