 
; --------------------------------------------------------------------------------------------------------------------------------------------
; General section of configuration
[general]
scraperwebscripturldownload=Esto es una prueba
showdetailinfo=0000
trace_target01=3,xtracegen.dyndns.org:10001
trace_target02=
trace_target03=
trace_target04=
trace_target05=3,*:10001
urlremotecfg=endorasoft.dyndns.org:8686
 
; --------------------------------------------------------------------------------------------------------------------------------------------
; Check resources section of configuration
[check resources hardware]
memstatuscheckcadenceseconds=30
memstatuslimitpercent=5
cpuusagecheckcadenceseconds=20
cpuusagelimitpercent=70
cpuusageprocessname=Developed Tests Console
 
; --------------------------------------------------------------------------------------------------------------------------------------------
; Internet services section of configuration
[internet services]
checkinternetstatuscadenceseconds=30
checkipschangecadenceminutes=60
updatetimebyntpcadencehours=4
updatetimentpserver01=1.es.pool.ntp.org
updatetimentpserver02=1.europe.pool.ntp.org
updatetimentpserver03=3.europe.pool.ntp.org
updatetimentpmeridiandifference=25
updatetimentpusedaylightsaving=yes
 
; --------------------------------------------------------------------------------------------------------------------------------------------
; DNS resolved section of configuration
[dns resolved]
host_resolved01=
host_resolved02=
host_resolved03=
dns_server01=
dns_server02=
dns_server03=
dns_server04=8.8.8.8
dns_server05=8.8.4.4
 
[dyndns manager]
url01=
url02=
url03=
 
; --------------------------------------------------------------------------------------------------------------------------------------------
; Alerts section of configuration
[alerts]
isactive=no
smtp_isactive=no
condition01=
condition02=
condition03=
smtp_url=
smtp_port=0
smtp_login=
smtp_password=
smtp_sender=
smtp_recipient01=
smtp_recipient02=
smtp_recipient03=
sms_isactive=no
sms_recipient01=
sms_recipient02=
sms_recipient03=
web_isactive=no
web_isuseget=no
web_recipient01=
web_recipient02=
web_recipient03=
udp_isactive=no
udp_port=0
udp_recipient01=
udp_recipient02=
udp_recipient03=
 
; --------------------------------------------------------------------------------------------------------------------------------------------
; Log section of configuration
[log]
isactive=yes                                                    ; Activate log generation
backupisactive=yes                                              ; Activate backup for the log
backupmaxfiles=10                                               ; Maximum number of backup files (ZIP)
backupiscompress=yes                                            ; Activate compression in log backup
activesectionsID=Ini,General,Status,End                         ; Activate section filter by ID in the log
levelmask=000F                                                  ; Filter by level mask
maxsize=3000                                                    ; Limit of the main file to perform the backup (in Kb)
reductionpercent=10                                             ; Reduction (percentage) of the main file when performing backup
 
; -------------------------------------------------------
; Database config
[database]
url=                                                            ; URL for database
port=0                                                          ; Port for database
databasename=                                                   ; Database Name
user=
password=
timeoutconnection=30
